# Generated by Django 3.2.7 on 2021-10-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaTvProqramları',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(help_text='Fotonun həcmi 570 uzunluğu 700 enni olmalıdır (570x700)', upload_to='media/')),
                ('yazı_1', models.CharField(help_text='Maksimum 40 simvol', max_length=40)),
                ('yazı_2', models.TextField(help_text='Maksimum 150 simvol', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='MediaYouTube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(help_text='Fotonun həcmi 570 uzunluğu 700 enni olmalıdır (570x700)', upload_to='media/')),
                ('link', models.TextField(help_text='Videonuzun Linkini Yükləyin', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MediaŞəkil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(help_text='Fotonun həcmi 570 uzunluğu 700 enni olmalıdır (570x700)', upload_to='media/')),
                ('yazı_1', models.CharField(help_text='Maksimum 40 simvol', max_length=40)),
                ('yazı_2', models.TextField(help_text='Maksimum 150 simvol', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='MediaƏsasŞəkil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='ƏsasŞəkilin_ÜstMətini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yazı_1', models.TextField(help_text='Maksimum 80 simvol', max_length=80)),
                ('yazı_2', models.TextField(help_text='Maksimum 70 simvol', max_length=70)),
            ],
        ),
    ]
