# Generated by Django 3.2.7 on 2021-10-17 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medi_app', '0002_auto_20211017_2106'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Müsahibə',
            new_name='Müsahibe',
        ),
    ]
