# Generated by Django 3.2.7 on 2021-11-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi_app', '0004_auto_20211116_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaTvProqramları',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(help_text='Fotonun həcmi 570 uzunluğu 700 enni olmalıdır (570x700)', upload_to='media/')),
                ('link_tv', models.CharField(help_text='Maksimum 40 simvol', max_length=40)),
                ('metn', models.TextField(help_text='Kicik metn', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='MediaYouTube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(help_text='Fotonun həcmi 570 uzunluğu 700 enni olmalıdır (570x700)', upload_to='media/')),
                ('link_youtube', models.TextField(help_text='Videonuzun Linkini Yükləyin', max_length=200)),
                ('metn', models.TextField(help_text='Kicik metn', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Müsahibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(help_text='Fotonun həcmi 570 uzunluğu 700 enni olmalıdır (570x700)', upload_to='media/')),
                ('link_musahibe', models.CharField(help_text='Maksimum 40 simvol', max_length=40)),
                ('metn', models.TextField(help_text='Kicik metn', max_length=1000)),
            ],
        ),
    ]
