# Generated by Django 3.2.7 on 2021-11-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi_app', '0005_mediatvproqramları_mediayoutube_müsahibe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediatvproqramları',
            name='link_tv',
            field=models.CharField(help_text='Maksimum 40 simvol', max_length=10000),
        ),
        migrations.AlterField(
            model_name='mediayoutube',
            name='link_youtube',
            field=models.TextField(help_text='Videonuzun Linkini Yükləyin', max_length=20000),
        ),
    ]
