# Generated by Django 3.2.15 on 2022-12-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi_app', '0006_auto_20211129_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='müsahibe',
            name='link_musahibe',
            field=models.CharField(help_text='Maksimum 10000 simvol', max_length=10000),
        ),
    ]
