# Generated by Django 3.2.7 on 2021-09-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Ad')),
                ('email', models.EmailField(max_length=25, verbose_name='Email')),
                ('subject', models.CharField(max_length=50, verbose_name='Mövzu')),
                ('message', models.TextField(max_length=255, verbose_name='Mesaj')),
            ],
        ),
    ]
