# Generated by Django 3.2.7 on 2021-09-16 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
