# Generated by Django 3.2.7 on 2021-09-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaytBashlig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bashlig', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
