# Generated by Django 3.2.7 on 2021-09-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0004_auto_20210917_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='BashligSekil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/bashligsekil')),
            ],
        ),
    ]
