# Generated by Django 3.2.7 on 2021-09-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0005_bashligsekil'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=10)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
