# Generated by Django 3.2.7 on 2021-09-17 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0006_numberemail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NumberEmail',
            new_name='BashligNomreEpoct',
        ),
    ]
