# Generated by Django 3.2.7 on 2021-09-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0008_alter_bashlignomreepoct_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bashlignomreepoct',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
