# Generated by Django 3.2.7 on 2021-09-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0009_alter_bashlignomreepoct_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlayderYazilar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yazi_1', models.CharField(max_length=100)),
                ('yazi_2', models.CharField(max_length=100)),
                ('yazi_3', models.CharField(max_length=100)),
            ],
        ),
    ]
