# Generated by Django 3.2.7 on 2021-09-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0010_slayderyazilar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slayderyazilar',
            name='yazi_1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='slayderyazilar',
            name='yazi_2',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='slayderyazilar',
            name='yazi_3',
            field=models.CharField(max_length=50),
        ),
    ]
