# Generated by Django 3.2.7 on 2021-09-17 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0012_auto_20210917_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slayderyazilar',
            name='yazi_3',
        ),
    ]
