# Generated by Django 3.2.7 on 2021-09-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0013_remove_slayderyazilar_yazi_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlayderSekil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.AlterField(
            model_name='bashligsekil',
            name='photo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
