# Generated by Django 3.2.7 on 2021-09-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0016_auto_20210917_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haqqimizdayazilar',
            name='yazi_3',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='haqqimizdayazilar',
            name='yazi_4',
            field=models.CharField(max_length=300),
        ),
    ]
