# Generated by Django 3.2.7 on 2021-09-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0017_auto_20210917_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Haqqimizdamuellif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adsoyad', models.CharField(max_length=30)),
                ('vezife', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
