# Generated by Django 3.2.7 on 2021-09-17 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0020_komandauzvleri'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Komandauzvleri',
        ),
    ]
