# Generated by Django 3.2.7 on 2021-09-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0021_delete_komandauzvleri'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServisUstYazilar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yazi_1', models.CharField(max_length=15)),
                ('yazi_2', models.CharField(max_length=30)),
            ],
        ),
    ]
