# Generated by Django 3.2.7 on 2021-09-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0022_servisustyazilar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServisMelumatAnaSeyfe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/')),
                ('servis_ust_yazi', models.CharField(max_length=15)),
                ('servis_kicik_melumat', models.TextField(max_length=30)),
            ],
        ),
    ]
