# Generated by Django 3.2.7 on 2021-09-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0023_servismelumatanaseyfe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haqqimizdayazilar',
            name='yazi_3',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='haqqimizdayazilar',
            name='yazi_4',
            field=models.TextField(max_length=300),
        ),
    ]
