# Generated by Django 3.2.7 on 2021-09-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0024_auto_20210918_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servismelumatanaseyfe',
            name='servis_kicik_melumat',
            field=models.TextField(max_length=60),
        ),
        migrations.AlterField(
            model_name='servismelumatanaseyfe',
            name='servis_ust_yazi',
            field=models.CharField(max_length=30),
        ),
    ]
