# Generated by Django 3.2.7 on 2021-09-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0025_auto_20210918_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servismelumatanaseyfe',
            name='servis_kicik_melumat',
            field=models.TextField(max_length=100),
        ),
    ]
