# Generated by Django 3.2.7 on 2021-09-18 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0027_alter_servismelumatanaseyfe_servis_kicik_melumat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servismelumatanaseyfe',
            old_name='img',
            new_name='balaca_sekil',
        ),
    ]
