# Generated by Django 3.2.7 on 2021-09-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0028_rename_img_servismelumatanaseyfe_balaca_sekil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servismelumatanaseyfe',
            name='servis_kicik_melumat',
            field=models.TextField(max_length=250),
        ),
    ]
