# Generated by Django 3.2.7 on 2021-09-18 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0029_alter_servismelumatanaseyfe_servis_kicik_melumat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servismelumatanaseyfe',
            old_name='balaca_sekil',
            new_name='balaca_sekil_hecmi_264_x_87',
        ),
    ]
