# Generated by Django 3.2.7 on 2021-09-18 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0030_rename_balaca_sekil_servismelumatanaseyfe_balaca_sekil_hecmi_264_x_87'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servismelumatanaseyfe',
            old_name='balaca_sekil_hecmi_264_x_87',
            new_name='balaca_sekil_hecmi_244_x_80',
        ),
    ]
