# Generated by Django 3.2.7 on 2021-09-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0031_rename_balaca_sekil_hecmi_264_x_87_servismelumatanaseyfe_balaca_sekil_hecmi_244_x_80'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servismelumatanaseyfe',
            name='balaca_sekil_hecmi_244_x_80',
            field=models.ImageField(height_field=80, upload_to='media/', width_field=244),
        ),
    ]
