# Generated by Django 3.2.7 on 2021-09-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0035_alter_servismelumatanaseyfe_balaca_sekil_hecmi_244_x_80'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bashligsekil',
            old_name='photo',
            new_name='bashligsekil',
        ),
        migrations.AlterField(
            model_name='servismelumatanaseyfe',
            name='balaca_sekil_hecmi_244_x_80',
            field=models.ImageField(help_text='Sekilin hecmi 244 uzunlugu 80 enni olmalidir (244x80)', upload_to='media/'),
        ),
    ]
