# Generated by Django 3.2.7 on 2021-09-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0036_auto_20210919_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoSekilAnaSeyfe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logosekilana', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
