# Generated by Django 3.2.7 on 2021-09-19 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0038_haqimizdasekiller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HaqimizdaSekiller',
        ),
    ]
