# Generated by Django 3.2.7 on 2021-09-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0042_auto_20210919_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='melumatsektoru',
            name='boyuk_yazi',
            field=models.CharField(help_text='Maksimum 40 simvol', max_length=40),
        ),
        migrations.AlterField(
            model_name='melumatsektoru',
            name='kicik_yazi',
            field=models.CharField(help_text='Maksimum 60 simvol', max_length=60),
        ),
    ]
