# Generated by Django 3.2.7 on 2021-09-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0044_auto_20210919_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='melumatsektoru',
            name='boyuk_yazi',
            field=models.TextField(help_text='Maksimum 45 simvol', max_length=45),
        ),
        migrations.AlterField(
            model_name='melumatsektoru',
            name='kicik_yazi',
            field=models.TextField(help_text='Maksimum 70 simvol', max_length=70),
        ),
    ]
