# Generated by Django 3.2.7 on 2021-09-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0045_auto_20210919_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='MukafatSektoru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sagalmis_xestelerin_sayi', models.CharField(help_text='Maksimum 10 simvol', max_length=10)),
                ('yazi_1', models.CharField(help_text='Maksimum 15 simvol', max_length=15)),
                ('kicik_metn_1', models.TextField(help_text='Maksimum 250 simvol', max_length=250)),
                ('mukafatlarin_sayi', models.CharField(help_text='Maksimum 10 simvol', max_length=10)),
                ('yazi_2', models.CharField(help_text='Maksimum 15 simvol', max_length=15)),
                ('kicik_metn_2', models.TextField(help_text='Maksimum 250 simvol', max_length=250)),
            ],
        ),
    ]
