# Generated by Django 3.2.7 on 2021-09-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0046_mukafatsektoru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mukafatsektoru',
            name='mukafatlarin_sayi',
            field=models.CharField(help_text='Maksimum 20 simvol', max_length=20),
        ),
        migrations.AlterField(
            model_name='mukafatsektoru',
            name='sagalmis_xestelerin_sayi',
            field=models.CharField(help_text='Maksimum 20 simvol', max_length=20),
        ),
    ]
