# Generated by Django 3.2.7 on 2021-09-19 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0047_auto_20210919_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mukafatsektoru',
            old_name='mukafatlarin_sayi',
            new_name='mukafat',
        ),
    ]
