# Generated by Django 3.2.7 on 2021-09-19 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0048_rename_mukafatlarin_sayi_mukafatsektoru_mukafat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MukafatSektoru',
        ),
    ]
