# Generated by Django 3.2.7 on 2021-09-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0049_delete_mukafatsektoru'),
    ]

    operations = [
        migrations.CreateModel(
            name='MukafatSektoru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslig_1', models.CharField(help_text='Maksimum 20 simvol', max_length=20)),
                ('sagalmis_xestelerin_sayi', models.CharField(help_text='Maksimum 15 simvol', max_length=15)),
                ('kicik_metn_1', models.TextField(help_text='Maksimum 250 simvol', max_length=250)),
                ('baslig_2', models.CharField(help_text='Maksimum 20 simvol', max_length=20)),
                ('mukafatlarin_sayi', models.CharField(help_text='Maksimum 15 simvol', max_length=15)),
                ('kicik_metn_2', models.TextField(help_text='Maksimum 250 simvol', max_length=250)),
            ],
        ),
    ]
