# Generated by Django 3.2.7 on 2021-09-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0050_mukafatsektoru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slaydersekil',
            name='image',
            field=models.ImageField(help_text='Tam fotonun keyfiyyetine 1282x700 olcu sekil yukleyin', upload_to='media/'),
        ),
    ]
