# Generated by Django 3.2.7 on 2021-09-20 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0051_alter_slaydersekil_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SlayderSekil',
            new_name='GirishSekil',
        ),
    ]
