# Generated by Django 3.2.7 on 2021-09-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0052_rename_slaydersekil_girishsekil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girishsekil',
            name='image',
            field=models.ImageField(help_text='Tam keyfiyyetine 1282x700 olcusunde foto yuklemeyinizin meslehet gorunur', upload_to='media/'),
        ),
    ]
