# Generated by Django 3.2.7 on 2021-09-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0053_alter_girishsekil_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girishsekil',
            name='image',
            field=models.ImageField(help_text='Tam keyfiyyətti 1282x700 ölçüsündə foto yükləməyinizin məsləhət görünür...', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='servismelumatanaseyfe',
            name='balaca_sekil_hecmi_244_x_80',
            field=models.ImageField(help_text='Fotonun həcmi 244 uzunluğu 80 enni olmalıdır (244x80)', upload_to='media/'),
        ),
    ]
