# Generated by Django 3.2.7 on 2021-09-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0054_auto_20210920_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqAnaSeyfeSagArxaFoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arxafonfoto', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
