# Generated by Django 3.2.7 on 2021-09-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0055_bloqanaseyfesagarxafoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqSolMetn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kicikmetn', models.CharField(help_text='Maksimum 70 simvol', max_length=70)),
                ('boyukyazi', models.CharField(help_text='Maksimum 45 simvol', max_length=45)),
            ],
        ),
        migrations.RenameModel(
            old_name='BloqAnaSeyfeSagArxaFoto',
            new_name='BloqAnaSeyfeSolArxaFoto',
        ),
    ]
