# Generated by Django 3.2.7 on 2021-09-20 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0057_auto_20210920_0955'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BloqXeberlerAnaSeyfe',
            new_name='BloqYeniXeberlerAnaSeyfe',
        ),
    ]
