# Generated by Django 3.2.7 on 2021-09-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0058_rename_bloqxeberleranaseyfe_bloqyenixeberleranaseyfe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='melumatsektoru',
            name='boyuk_yazi',
            field=models.TextField(help_text='Maksimum 100 simvol', max_length=100),
        ),
        migrations.AlterField(
            model_name='melumatsektoru',
            name='kicik_yazi',
            field=models.TextField(help_text='Maksimum 150 simvol', max_length=150),
        ),
    ]
