# Generated by Django 3.2.7 on 2021-09-20 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0060_auto_20210920_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloqyenixeberleranaseyfe',
            name='tarix',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
