# Generated by Django 3.2.7 on 2021-09-20 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0063_auto_20210920_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloqyenixeberleranaseyfe',
            name='kicikmetn',
            field=models.CharField(help_text='Maksimum 200 simvol', max_length=20),
        ),
        migrations.AlterField(
            model_name='bloqyenixeberleranaseyfe',
            name='tarix',
            field=models.DateField(default=django.utils.timezone.now, help_text='Avtomatik ozü vaxtı təyin edir'),
        ),
        migrations.AlterField(
            model_name='bloqyenixeberleranaseyfe',
            name='ustmetn',
            field=models.TextField(help_text='Maksimum 80 simvol', max_length=200),
        ),
    ]
