# Generated by Django 3.2.7 on 2021-09-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0064_auto_20210920_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeciliInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basliq', models.CharField(help_text='Maksimum 60 simvol', max_length=60)),
                ('elaqenomresi', models.IntegerField(help_text='Maksimum 50 simvol', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='bloqyenixeberleranaseyfe',
            name='kicikmetn',
            field=models.CharField(help_text='Maksimum 20 simvol', max_length=20),
        ),
        migrations.AlterField(
            model_name='bloqyenixeberleranaseyfe',
            name='ustmetn',
            field=models.TextField(help_text='Maksimum 200 simvol', max_length=200),
        ),
    ]
