# Generated by Django 3.2.7 on 2021-09-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0065_auto_20210920_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teciliinfo',
            name='elaqenomresi',
            field=models.CharField(help_text='Maksimum 50 simvol', max_length=50),
        ),
    ]
