# Generated by Django 3.2.7 on 2021-09-20 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0066_alter_teciliinfo_elaqenomresi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeciliInfo',
        ),
    ]
