# Generated by Django 3.2.7 on 2021-09-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0067_delete_teciliinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeciliInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basliq', models.CharField(help_text='Maksimum 60 simvol', max_length=60)),
                ('elaqenomresi', models.CharField(help_text='Maksimum 50 simvol', max_length=50)),
                ('sekil', models.ImageField(help_text='Məsləhət görünür Kiçik Foto', upload_to='media/')),
                ('metn', models.TextField(help_text='Maksimum 50 simvol', max_length=250)),
                ('elaqepoct', models.EmailField(help_text='Maksimum 80 simvol', max_length=80)),
                ('mekan', models.CharField(help_text='Maksimum 100 simvol', max_length=100)),
            ],
        ),
    ]
