# Generated by Django 3.2.7 on 2021-09-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0069_auto_20210920_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloqyenixeberleranaseyfe',
            name='ustmetn',
            field=models.TextField(help_text='Maksimum 100 simvol', max_length=100),
        ),
    ]
