# Generated by Django 3.2.7 on 2021-09-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0070_alter_bloqyenixeberleranaseyfe_ustmetn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloqyenixeberleranaseyfe',
            name='ustmetn',
            field=models.TextField(help_text='Maksimum 70 simvol', max_length=70),
        ),
    ]
