# Generated by Django 3.2.7 on 2021-09-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0071_alter_bloqyenixeberleranaseyfe_ustmetn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloqyenixeberleranaseyfe',
            name='foto',
        ),
    ]
