# Generated by Django 3.2.7 on 2021-09-20 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0072_remove_bloqyenixeberleranaseyfe_foto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloqYeniXeberlerAnaSeyfe',
        ),
        migrations.DeleteModel(
            name='TeciliElektronElaqe',
        ),
    ]
