# Generated by Django 3.2.7 on 2021-09-20 13:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0073_auto_20210920_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqYeniXeberlerAnaSeyfe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='media/')),
                ('kicikmetn', models.CharField(help_text='Maksimum 20 simvol', max_length=20)),
                ('ustmetn', models.TextField(help_text='Maksimum 70 simvol', max_length=70)),
                ('etraflimelumat', models.TextField(help_text='Maksimum 250 simvol', max_length=250)),
                ('tarix', models.DateField(default=django.utils.timezone.now, help_text='Avtomatik ozü vaxtı təyin edir')),
            ],
        ),
        migrations.CreateModel(
            name='TeciliElektronElaqe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metn', models.TextField(help_text='Maksimum 50 simvol', max_length=250)),
                ('elaqepoct', models.EmailField(help_text='Maksimum 80 simvol', max_length=80)),
                ('mekan', models.CharField(help_text='Maksimum 100 simvol', max_length=100)),
            ],
        ),
    ]
