# Generated by Django 3.2.7 on 2021-09-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0074_bloqyenixeberleranaseyfe_tecilielektronelaqe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
