# Generated by Django 3.2.7 on 2021-09-21 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0075_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
