# Generated by Django 3.2.7 on 2021-09-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0076_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Haqqımızdamüəllif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adsoyad', models.CharField(help_text='Maksimum 30 simvol', max_length=30)),
                ('vezife', models.CharField(help_text='Maksimum 15 simvol', max_length=15)),
            ],
        ),
        migrations.RenameModel(
            old_name='BashligNomreEpoct',
            new_name='BaşlıqNömrəEpoct',
        ),
        migrations.RenameModel(
            old_name='BashligSekil',
            new_name='Bloq_AnaSəhifə_SolArxaFoto',
        ),
        migrations.RenameModel(
            old_name='BloqYeniXeberlerAnaSeyfe',
            new_name='Bloq_YeniXəbərlər_AnaSehifə',
        ),
        migrations.RenameModel(
            old_name='BloqSolMetn',
            new_name='BloqSolMətn',
        ),
        migrations.RenameModel(
            old_name='GirishSekil',
            new_name='GirişŞəkil',
        ),
        migrations.RenameModel(
            old_name='SlayderYazilar',
            new_name='GirişŞəkilYazılar',
        ),
        migrations.RenameModel(
            old_name='HaqqimizdaYazilar',
            new_name='HaqqımızdaYazılar',
        ),
        migrations.RenameModel(
            old_name='HaqimizdaSekiller',
            new_name='HaqqımızdaŞəkillər',
        ),
        migrations.RenameModel(
            old_name='Komandayazi',
            new_name='Komanda_Haqqında_yazılar',
        ),
        migrations.RenameModel(
            old_name='LogoSekilAnaSeyfe',
            new_name='LogoŞəkilAnaSəhifə',
        ),
        migrations.RenameModel(
            old_name='MukafatSektoru',
            new_name='MükafatSektoru',
        ),
        migrations.RenameModel(
            old_name='MelumatSektoru',
            new_name='MəlumatSektoru',
        ),
        migrations.RenameModel(
            old_name='SaytBashlig',
            new_name='SaytınBaşlığı',
        ),
        migrations.RenameModel(
            old_name='BloqAnaSeyfeSolArxaFoto',
            new_name='SaytınBaşlığıFoto',
        ),
        migrations.RenameModel(
            old_name='ServisMelumatAnaSeyfe',
            new_name='Servis_Məlümat_AnaSəhifə',
        ),
        migrations.RenameModel(
            old_name='ServisUstYazilar',
            new_name='Servis_Üst_Yazılar',
        ),
        migrations.RenameModel(
            old_name='TeciliElektronElaqe',
            new_name='TəciliElektron_Əlaqe',
        ),
        migrations.RenameModel(
            old_name='TeciliInfo',
            new_name='TəciliInfo',
        ),
        migrations.DeleteModel(
            name='Haqqimizdamuellif',
        ),
        migrations.RenameField(
            model_name='bloq_anasəhifə_solarxafoto',
            old_name='bashligsekil',
            new_name='arxafonfoto',
        ),
        migrations.RenameField(
            model_name='saytınbaşlığıfoto',
            old_name='arxafonfoto',
            new_name='bashligsekil',
        ),
    ]
