# Generated by Django 3.2.7 on 2021-09-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0077_auto_20210922_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasiyentlərinRəyi_Slayder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulduz', models.ImageField(upload_to='media/')),
                ('metn', models.TextField(help_text='Maksimum 200 hərif', max_length=200)),
                ('instagram', models.CharField(help_text='Maksimum 40 hərif', max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='başlıqnömrəepoct',
            name='email',
            field=models.CharField(help_text='Maksimum 30 hərif', max_length=30),
        ),
        migrations.AlterField(
            model_name='başlıqnömrəepoct',
            name='number',
            field=models.CharField(help_text='Maksimum 20 hərif', max_length=20),
        ),
        migrations.AlterField(
            model_name='bloq_yenixəbərlər_anasehifə',
            name='etraflimelumat',
            field=models.TextField(help_text='Maksimum 250 hərif', max_length=250),
        ),
        migrations.AlterField(
            model_name='bloq_yenixəbərlər_anasehifə',
            name='kicikmetn',
            field=models.CharField(help_text='Maksimum 20 hərif', max_length=20),
        ),
        migrations.AlterField(
            model_name='bloq_yenixəbərlər_anasehifə',
            name='ustmetn',
            field=models.TextField(help_text='Maksimum 70 hərif', max_length=70),
        ),
        migrations.AlterField(
            model_name='bloqsolmətn',
            name='boyukyazi',
            field=models.TextField(help_text='Maksimum 45 hərif', max_length=45),
        ),
        migrations.AlterField(
            model_name='bloqsolmətn',
            name='kicikmetn',
            field=models.CharField(help_text='Maksimum 70 hərif', max_length=70),
        ),
        migrations.AlterField(
            model_name='girişşəkilyazılar',
            name='yazi_1',
            field=models.CharField(help_text='Maksimum 50 hərif', max_length=50),
        ),
        migrations.AlterField(
            model_name='girişşəkilyazılar',
            name='yazi_2',
            field=models.CharField(help_text='Maksimum 30 hərif', max_length=30),
        ),
        migrations.AlterField(
            model_name='haqqımızdamüəllif',
            name='adsoyad',
            field=models.CharField(help_text='Maksimum 30 hərif', max_length=30),
        ),
        migrations.AlterField(
            model_name='haqqımızdamüəllif',
            name='vezife',
            field=models.CharField(help_text='Maksimum 15 hərif', max_length=15),
        ),
        migrations.AlterField(
            model_name='haqqımızdayazılar',
            name='yazi_1',
            field=models.CharField(help_text='Maksimum 30 hərif', max_length=30),
        ),
        migrations.AlterField(
            model_name='haqqımızdayazılar',
            name='yazi_2',
            field=models.CharField(help_text='Maksimum 35 hərif', max_length=35),
        ),
        migrations.AlterField(
            model_name='haqqımızdayazılar',
            name='yazi_3',
            field=models.TextField(help_text='Maksimum 200 hərif', max_length=200),
        ),
        migrations.AlterField(
            model_name='haqqımızdayazılar',
            name='yazi_4',
            field=models.TextField(help_text='Maksimum 300 hərif', max_length=300),
        ),
        migrations.AlterField(
            model_name='komanda_haqqında_yazılar',
            name='komanda',
            field=models.CharField(help_text='Maksimum 20 hərif', max_length=20),
        ),
        migrations.AlterField(
            model_name='komanda_haqqında_yazılar',
            name='komandayazi',
            field=models.CharField(help_text='Maksimum 30 hərif', max_length=30),
        ),
        migrations.AlterField(
            model_name='mükafatsektoru',
            name='baslig_1',
            field=models.CharField(help_text='Maksimum 20 hərif', max_length=20),
        ),
        migrations.AlterField(
            model_name='mükafatsektoru',
            name='baslig_2',
            field=models.CharField(help_text='Maksimum 20 hərif', max_length=20),
        ),
        migrations.AlterField(
            model_name='mükafatsektoru',
            name='kicik_metn_1',
            field=models.TextField(help_text='Maksimum 250 hərif', max_length=250),
        ),
        migrations.AlterField(
            model_name='mükafatsektoru',
            name='kicik_metn_2',
            field=models.TextField(help_text='Maksimum 250 hərif', max_length=250),
        ),
        migrations.AlterField(
            model_name='mükafatsektoru',
            name='mukafatlarin_sayi',
            field=models.CharField(help_text='Maksimum 15 hərif', max_length=15),
        ),
        migrations.AlterField(
            model_name='mükafatsektoru',
            name='sagalmis_xestelerin_sayi',
            field=models.CharField(help_text='Maksimum 15 hərif', max_length=15),
        ),
        migrations.AlterField(
            model_name='məlumatsektoru',
            name='boyuk_yazi',
            field=models.TextField(help_text='Maksimum 150 hərif', max_length=150),
        ),
        migrations.AlterField(
            model_name='məlumatsektoru',
            name='kicik_yazi',
            field=models.TextField(help_text='Maksimum 200 hərif', max_length=200),
        ),
        migrations.AlterField(
            model_name='saytınbaşlığı',
            name='bashlig',
            field=models.CharField(help_text='Maksimum 20 hərif', max_length=20),
        ),
        migrations.AlterField(
            model_name='servis_məlümat_anasəhifə',
            name='servis_kicik_melumat',
            field=models.TextField(help_text='Maksimum 250 hərif', max_length=250),
        ),
        migrations.AlterField(
            model_name='servis_məlümat_anasəhifə',
            name='servis_ust_yazi',
            field=models.CharField(help_text='Maksimum 30 hərif', max_length=30),
        ),
        migrations.AlterField(
            model_name='servis_üst_yazılar',
            name='yazi_1',
            field=models.CharField(help_text='Maksimum 15 hərif', max_length=15),
        ),
        migrations.AlterField(
            model_name='servis_üst_yazılar',
            name='yazi_2',
            field=models.CharField(help_text='Maksimum 30 hərif', max_length=30),
        ),
        migrations.AlterField(
            model_name='təcilielektron_əlaqe',
            name='elaqepoct',
            field=models.EmailField(help_text='Maksimum 80 hərif', max_length=80),
        ),
        migrations.AlterField(
            model_name='təcilielektron_əlaqe',
            name='mekan',
            field=models.CharField(help_text='Maksimum 100 hərif', max_length=100),
        ),
        migrations.AlterField(
            model_name='təcilielektron_əlaqe',
            name='metn',
            field=models.TextField(help_text='Maksimum 250 hərif', max_length=250),
        ),
        migrations.AlterField(
            model_name='təciliinfo',
            name='basliq',
            field=models.CharField(help_text='Maksimum 60 hərif', max_length=60),
        ),
        migrations.AlterField(
            model_name='təciliinfo',
            name='elaqenomresi',
            field=models.CharField(help_text='Maksimum 50 hərif', max_length=50),
        ),
    ]
