# Generated by Django 3.2.7 on 2021-09-28 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0078_auto_20210925_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pasiyentlərinrəyi_slayder',
            old_name='ulduz',
            new_name='foto',
        ),
        migrations.AddField(
            model_name='pasiyentlərinrəyi_slayder',
            name='vaxt',
            field=models.DateField(default=django.utils.timezone.now, help_text='Avtomatik ozü vaxtı təyin edir'),
        ),
        migrations.AlterField(
            model_name='pasiyentlərinrəyi_slayder',
            name='metn',
            field=models.TextField(help_text='Maksimum 300 hərif', max_length=300),
        ),
    ]
