# Generated by Django 3.2.7 on 2021-09-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0081_auto_20210929_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tez_tez_verilənsuallar',
            name='cavab',
            field=models.TextField(help_text='Maksimum 1000 hərif', max_length=1000),
        ),
        migrations.AlterField(
            model_name='tez_tez_verilənsuallar',
            name='sual',
            field=models.TextField(help_text='Maksimum 200 hərif', max_length=200),
        ),
    ]
