# Generated by Django 3.2.7 on 2021-10-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0082_auto_20210929_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girişşəkil',
            name='image',
            field=models.ImageField(help_text='Tam keyfiyyətti 1282x700 ölçüsündə foto yükləməyinizin məsləhət görünür...', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='saytınbaşlığıfoto',
            name='bashligsekil',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
