# Generated by Django 3.2.7 on 2021-10-10 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0083_auto_20211008_0947'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TəciliElektron_Əlaqe',
        ),
        migrations.DeleteModel(
            name='TəciliInfo',
        ),
    ]
