# Generated by Django 3.2.7 on 2021-10-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0084_auto_20211010_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haqqımızdayazılar',
            name='yazi_1',
            field=models.CharField(help_text='Maksimum 500 hərif', max_length=500),
        ),
        migrations.AlterField(
            model_name='haqqımızdayazılar',
            name='yazi_4',
            field=models.TextField(help_text='Maksimum 5000 hərif', max_length=5000),
        ),
    ]
