# Generated by Django 3.2.7 on 2021-10-18 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0085_auto_20211016_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='haqqımızdayazılar',
            name='yazi_1',
        ),
    ]
