# Generated by Django 3.2.7 on 2021-11-16 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0088_auto_20211029_0830'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Footer_Bloq',
        ),
    ]
