# Generated by Django 3.2.7 on 2021-11-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0089_delete_footer_bloq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer_Bloq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_1', models.ImageField(upload_to='media/')),
                ('bloq_1_seyfenin_bashliq_postu', models.TextField(help_text='Maksimum 300 hərif', max_length=300)),
                ('vaxt_1', models.DateField()),
                ('foto_2', models.ImageField(upload_to='media/')),
                ('bloq_2_seyfenin_bashliq_postu', models.TextField(help_text='Maksimum 300 hərif', max_length=300)),
                ('vaxt_2', models.DateField()),
                ('foto_3', models.ImageField(upload_to='media/')),
                ('bloq_3_seyfenin_bashliq_postu', models.TextField(help_text='Maksimum 300 hərif', max_length=300)),
                ('vaxt_3', models.DateField()),
            ],
        ),
    ]
