# Generated by Django 3.2.7 on 2021-11-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0090_footer_bloq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube_Link_Əsas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_link', models.TextField(help_text='Youtube Video Linki', max_length=5000)),
            ],
        ),
    ]
