# Generated by Django 3.2.7 on 2021-11-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0091_youtube_link_əsas'),
    ]

    operations = [
        migrations.AddField(
            model_name='başlıqnömrəepoct',
            name='clock',
            field=models.CharField(default='', help_text='Maksimum 200 hərif', max_length=200),
        ),
    ]
