# Generated by Django 3.2.7 on 2021-11-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0092_başlıqnömrəepoct_clock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bloq_AnaSəhifə_SolArxaFoto',
            new_name='MobileFoto',
        ),
        migrations.DeleteModel(
            name='Komanda_Haqqında_yazılar',
        ),
        migrations.RenameField(
            model_name='mobilefoto',
            old_name='arxafonfoto',
            new_name='foto',
        ),
        migrations.AlterField(
            model_name='başlıqnömrəepoct',
            name='clock',
            field=models.CharField(help_text='Maksimum 200 hərif', max_length=200),
        ),
    ]
