# Generated by Django 3.2.7 on 2021-11-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0093_auto_20211125_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobilefoto',
            old_name='foto',
            new_name='foto_res',
        ),
    ]
