# Generated by Django 3.2.15 on 2022-12-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0096_auto_20221216_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='saytınbaşlığıfoto',
            name='apple_icon',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
