# Generated by Django 3.2.7 on 2021-09-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BizəZəng',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metn', models.CharField(help_text='Maksimum 50 hərif', max_length=50)),
                ('nomre', models.CharField(help_text='Maksimum 50 simvol', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail', models.CharField(help_text='Maksimum 50 hərif', max_length=50)),
                ('ustmetn', models.CharField(help_text='Maksimum 50 hərif', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Məkan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ustmetn', models.CharField(help_text='Maksimum 50 hərif', max_length=50)),
                ('mekan', models.TextField(help_text='Maksimum 100 həif', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ƏsasFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='ƏsasFotoMətnlər',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metn_1', models.TextField(help_text='Maksimum 80 hərif', max_length=80)),
                ('metn_2', models.TextField(help_text='Maksimum 200 hərif', max_length=200)),
            ],
        ),
    ]
