# Generated by Django 3.2.7 on 2021-09-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0004_alter_bizəzəng_nomre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmail',
            name='gmail',
            field=models.EmailField(help_text='Maksimum 50 hərif', max_length=50),
        ),
    ]
