# Generated by Django 3.2.7 on 2021-10-17 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0005_alter_gmail_gmail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bizəzəng',
            name='metn',
        ),
        migrations.RemoveField(
            model_name='gmail',
            name='ustmetn',
        ),
        migrations.RemoveField(
            model_name='məkan',
            name='ustmetn',
        ),
    ]
