# Generated by Django 3.2.7 on 2021-11-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0006_auto_20211017_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Üst_Şəkil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='media/')),
            ],
        ),
    ]
