# Generated by Django 3.2.7 on 2021-11-25 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0007_üst_şəkil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ƏsasFoto',
        ),
    ]
