# Generated by Django 3.2.7 on 2021-11-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0008_delete_əsasfoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileƏsasFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='media/')),
            ],
        ),
    ]
