# Generated by Django 3.2.7 on 2021-10-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigərServislər',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servisin_adi', models.CharField(help_text='Maksimum 50 hərif', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Muellif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fikirleriniz', models.TextField(help_text='Maksimum 600 hərif', max_length=600)),
                ('ad_soyad', models.TextField(help_text='Maksimum 100 hərif', max_length=100)),
                ('vezifeniz', models.CharField(help_text='Maksimum 80 hərif', max_length=80)),
                ('foto', models.ImageField(help_text='Fotonun həcmi 100 uzunluğu 100 enni olmalıdır (100x100)', upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Sagbaner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sag_baner', models.ImageField(help_text='Fotonun həcmi 470 uzunluğu 600 enni olmalıdır (470x600)', upload_to='', verbose_name='media/')),
            ],
        ),
        migrations.CreateModel(
            name='ServisMəlumat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sag_melumat', models.CharField(help_text='Maksimum 50 hərif', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Xidmətlərimiz_Haqqında',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esas_foto', models.ImageField(upload_to='media/')),
                ('haqqimizda_ust_yazi_1', models.TextField(help_text='Maksimum 500 hərif', max_length=500)),
                ('haqqimizda_ust_yazi_2', models.TextField(help_text='Maksimum 500 hərif', max_length=500)),
                ('xett_foto', models.ImageField(upload_to='media/')),
                ('metn', models.TextField(help_text='Maksimum 10000 hərif', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='ƏsasFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esas_foto', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='ƏsasFoto_ÜstYazılar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metn_1', models.TextField(help_text='Maksimum 100 hərif', max_length=100)),
                ('metn_2', models.TextField(help_text='Maksimum 100 hərif', max_length=80)),
            ],
        ),
    ]
