# Generated by Django 3.2.7 on 2021-11-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xidmetler_app', '0003_xidmətlərimiz_haqqında'),
    ]

    operations = [
        migrations.CreateModel(
            name='Məlumat_Sektoru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kicik_metn', models.TextField(help_text='Maksimum 500 hərif', max_length=500)),
                ('bashliq', models.TextField(help_text='Maksimum 1500 hərif', max_length=1500)),
                ('metn', models.TextField(help_text='Maksimum 5000 hərif', max_length=5000)),
            ],
        ),
        migrations.DeleteModel(
            name='DigərServislər',
        ),
        migrations.DeleteModel(
            name='Muellif',
        ),
        migrations.DeleteModel(
            name='Sagbaner',
        ),
        migrations.DeleteModel(
            name='ServisMəlumat',
        ),
    ]
