# Generated by Django 3.2.7 on 2021-11-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xidmetler_app', '0004_auto_20211116_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xidmətlər_Postları',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='media/')),
                ('bashliq', models.TextField(max_length=1000)),
                ('vaxt', models.DateTimeField()),
            ],
        ),
    ]
