# Generated by Django 3.2.7 on 2021-11-27 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xidmetler_app', '0005_xidmətlər_postları'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='əsasfoto_üstyazılar',
            name='metn_1',
        ),
    ]
