# Generated by Django 3.2.15 on 2022-12-16 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xidmetler_app', '0006_remove_əsasfoto_üstyazılar_metn_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='məlumat_sektoru',
            name='metn',
        ),
    ]
