# Generated by Django 3.2.15 on 2022-12-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xidmetler_app', '0007_remove_məlumat_sektoru_metn'),
    ]

    operations = [
        migrations.AddField(
            model_name='xidmətlərimiz_haqqında',
            name='description',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='xidmətlərimiz_haqqında',
            name='keyword',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='xidmətlərimiz_haqqında',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='xidmətlərimiz_haqqında',
            name='title',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
    ]
