# Generated by Django 3.2.15 on 2022-12-16 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xidmetler_app', '0008_auto_20221216_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xidmətlərimiz_haqqında',
            options={'verbose_name': 'Xidmətlər', 'verbose_name_plural': 'Xidmətlər'},
        ),
    ]
