# Generated by Django 3.2.15 on 2022-12-19 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('xidmetler_app', '0009_alter_xidmətlərimiz_haqqında_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='xidmətlərimiz_haqqında',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Vaxtı avtomatik olaraq özü təyin edəcək'),
        ),
    ]
