# Generated by Django 3.2.7 on 2021-09-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qebul_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ƏsasŞəkilinYazıları',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yazı_1', models.CharField(help_text='Maksimum 50 simvol', max_length=50)),
                ('yazı_2', models.CharField(help_text='Maksimum 20 simvol', max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='EsasSekil',
            new_name='ƏsasŞəkil',
        ),
    ]
