# Generated by Django 3.2.7 on 2021-09-22 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qebul_app', '0002_auto_20210922_0904'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ƏsasŞəkil',
            new_name='Əsas_Şəkil',
        ),
        migrations.RenameModel(
            old_name='ƏsasŞəkilinYazıları',
            new_name='Əsas_Şəkilin_Yazıları',
        ),
    ]
