# Generated by Django 3.2.7 on 2021-09-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qebul_app', '0003_auto_20210922_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='əsas_şəkilin_yazıları',
            name='yazı_1',
            field=models.CharField(help_text='Maksimum 50 simvol', max_length=80),
        ),
        migrations.AlterField(
            model_name='əsas_şəkilin_yazıları',
            name='yazı_2',
            field=models.CharField(help_text='Maksimum 20 simvol', max_length=35),
        ),
    ]
