# Generated by Django 3.2.7 on 2021-09-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qebul_app', '0005_auto_20210922_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qəbul_Form_Arxa_Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
