# Generated by Django 3.2.7 on 2021-09-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qebul_app', '0007_qəbulxəritə'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qəbulxəritə',
            name='xerite_url',
            field=models.TextField(help_text='Google Xəritənin Linki', max_length=500),
        ),
    ]
