# Generated by Django 3.2.7 on 2021-10-02 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qebul_app', '0008_alter_qəbulxəritə_xerite_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Qəbul_Haqqımızda_foto',
        ),
    ]
