# Generated by Django 3.2.7 on 2021-10-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qebul_app', '0009_delete_qəbul_haqqımızda_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qəbul_Haqqımızda_foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esasfoto', models.ImageField(upload_to='media/')),
                ('ortafoto', models.ImageField(upload_to='media/')),
                ('youtube_url', models.TextField(help_text='Youtube kanalınızın linki', max_length=500)),
            ],
        ),
    ]
