# Generated by Django 3.2.7 on 2021-11-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qebul_app', '0010_qəbul_haqqımızda_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qəbula_Yazıl_Forma_Arxa_Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
