# Generated by Django 3.2.7 on 2021-11-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qebul_app', '0011_qəbula_yazıl_forma_arxa_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Üst_Şəkil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='Əsas_Şəkil',
        ),
    ]
