# Generated by Django 3.2.7 on 2021-11-17 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qebul_app', '0012_auto_20211117_1228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Üst_Şəkil',
        ),
    ]
