# Generated by Django 3.2.7 on 2021-11-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qebul_app', '0013_delete_üst_şəkil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Əsas_Şəkil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esassekil', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
