# Generated by Django 3.2.15 on 2022-12-16 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qebul_app', '0014_əsas_şəkil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Qəbul_Form_Arxa_Foto',
        ),
        migrations.DeleteModel(
            name='Qəbula_Yazıl_Forma_Arxa_Foto',
        ),
    ]
