# Generated by Django 3.2.7 on 2021-09-30 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HaqqımdaMəlumat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='media/')),
                ('ad_soyad', models.CharField(help_text='Maksimum 100 hərif', max_length=100)),
                ('kicik_metn', models.TextField(help_text='Maksimum 300 hərif', max_length=300)),
                ('facebook_url', models.TextField(help_text='FaceBook profilinizin Linki', max_length=500)),
                ('youtube_url', models.TextField(help_text='YouTube kanalinizin Linki', max_length=500)),
                ('instagram_url', models.TextField(help_text='Instagram profilinizin Linki', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PostPaylaşılma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_post', models.ImageField(upload_to='media/')),
                ('vaxt', models.DateTimeField(default=django.utils.timezone.now, help_text='Vaxtı avtomatik olaraq ozü təyin edəcək')),
                ('ad_soyad', models.CharField(help_text='Maksimum 80 hərif', max_length=80)),
                ('metinin_bashligi', models.TextField(help_text='Maksimum 150 hərif', max_length=150)),
                ('metn', models.TextField(help_text='Maksimum 800 hərif', max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='ƏsasFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esas_foto', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='ƏsasFoto_ÜstMətn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metn_1', models.TextField(help_text='Maksimum 100 hərif', max_length=100)),
                ('metn_2', models.TextField(help_text='Maksimum 150 hərif', max_length=150)),
            ],
        ),
    ]
