# Generated by Django 3.2.7 on 2021-09-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpaylaşılma',
            name='foto_post',
            field=models.ImageField(help_text='770x561 Həcmində foto yükləməyinizi məsləhət görünür', upload_to='media/'),
        ),
    ]
