# Generated by Django 3.2.7 on 2021-10-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_postpaylaşılma_foto_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hekayə',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hekaye', models.TextField(help_text='Maksimum 150 hərif', max_length=150)),
                ('muellif', models.CharField(help_text='Maksimum 80 hərif', max_length=80)),
            ],
        ),
    ]
