# Generated by Django 3.2.7 on 2021-10-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_hekayə'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hekayə',
            name='hekaye',
            field=models.TextField(help_text='Maksimum 500 hərif', max_length=500),
        ),
    ]
