# Generated by Django 3.2.7 on 2021-10-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_hekayə_hekaye'),
    ]

    operations = [
        migrations.CreateModel(
            name='SosialŞəbəkəLinkləri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_url', models.TextField(help_text='FaceBook profilinizin Linki', max_length=500)),
                ('youtube_url', models.TextField(help_text='YouTube kanalinizin Linki', max_length=500)),
                ('instagram_url', models.TextField(help_text='Instagram profilinizin Linki', max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='HaqqımdaMəlumat',
        ),
    ]
