# Generated by Django 3.2.7 on 2021-11-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_auto_20211020_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Digər_Bloqlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='media/')),
                ('bashliq', models.TextField(max_length=1000)),
                ('vaxt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Footer_Açılış_Vaxtları',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hefteler', models.TextField(help_text='Maksimum 500 hərif', max_length=500)),
                ('vaxt_1', models.TimeField()),
                ('istirahet_gunleri', models.TextField(help_text='Maksimum 500 hərif', max_length=500)),
                ('vaxt_2', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Footer_Yazısı',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metn', models.TextField(help_text='Maksimum 2000 hərif', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Haqqımda_Məlumat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='media/')),
                ('ad_soyad', models.CharField(help_text='Maksimum 150 hərif', max_length=150)),
                ('kicik_metn', models.TextField(help_text='Maksimum 1000 hərif', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='İnstagram_Postları',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_link', models.TextField(help_text='Instagram Postun Linki', max_length=1000)),
                ('foto', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
