# Generated by Django 3.2.7 on 2021-11-29 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_auto_20211116_2107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hekayə',
        ),
    ]
