# Generated by Django 3.2.15 on 2022-12-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_delete_hekayə'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEO_Bloq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metatag', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='postpaylaşılma',
            name='metn',
            field=models.TextField(),
        ),
    ]
