# Generated by Django 3.2.15 on 2022-12-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_auto_20221216_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpaylaşılma',
            name='description',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='postpaylaşılma',
            name='keyword',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='postpaylaşılma',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='postpaylaşılma',
            name='title',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
    ]
