# Generated by Django 3.2.15 on 2022-12-16 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_auto_20221216_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postpaylaşılma',
            options={'verbose_name': 'Bloqlar', 'verbose_name_plural': 'Bloqlar'},
        ),
    ]
