# Generated by Django 3.2.15 on 2022-12-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_alter_postpaylaşılma_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpaylaşılma',
            name='metinin_bashligi',
            field=models.TextField(help_text='Maksimum 150 hərif', max_length=550),
        ),
    ]
